### ISSUE TITLE
npm scripts

### ISSUE THREAD

**Issue by vladimirstarkov** [andrepolischuk/typographic-arrows#1]
why do you need makefile, if you have npm scripts for that?

**Comment by andrepolischuk** [comment]
@vladimirstarkov Before i had some projects without package.json and used makefile for assembling. And I'm still using.

**Comment by vladimirstarkov** [comment]
it is more common to use OS-independent workflow. what do you think about it?

**Comment by andrepolischuk** [comment]
I like `target: ...dependencies` in Makefile and I think that os-independent it's great. I'll try to use scripts instead of Makefile.

**Comment by vladimirstarkov** [comment]
I cannot see `target …dependencies` in your [Makefile](https://github.com/andrepolischuk/typographic-arrows/blob/master/Makefile).

> I'll try to use scripts instead of Makefile.

Maybe pull-requests are we welcomed, then I can help you here

**Comment by andrepolischuk** [comment]
You can send

**Comment by vladimirstarkov** [comment]
Submitted #2
