### ISSUE TITLE
conflicts with typographic-math-symbols

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/typographic-arrows#3]
> https://github.com/vladimirstarkov/typographic-math-symbols/blob/master/index.js#L7-L8

    .replace(/(\w) >= (\w)/gim, '$1 ≥ $2')
    .replace(/(\w) <= (\w)/gim, '$1 ≤ $2')

vs

> https://github.com/andrepolischuk/typographic-arrows/blob/master/index.js#L15-L16

    .replace(/<=/gim, '⇐')
    .replace(/=>/gim, '⇒');

How do you think is there any way to proper matching each pattern and processing it with appropriate module?

**Comment by andrepolischuk** [comment]
May be use `=<` instead of `<=` in typographic-math? What do you think?

**Comment by iamstarkov** [comment]
yeah, your solution is good enough. let’s do it
