### ISSUE TITLE
version 1.0

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/typographic-arrows#4]
is it already ready and mature for major bump?

**Comment by andrepolischuk** [comment]
Bumped and published to npm

**Comment by iamstarkov** [comment]
awsm, thank you

**Comment by iamstarkov** [comment]
why dont you star your own project?

**Comment by andrepolischuk** [comment]
I star sometimes

**Comment by iamstarkov** [comment]
I’m usually doing it after v1 to show that project is ready to use
